@startuml
actor User
User -> 決策桌: 創建決策桌要求
activate 決策桌
決策桌 -> 決策桌: 驗證資料是否合法
activate 決策桌
決策桌 <-- 決策桌: 回應結果
deactivate 決策桌
alt 合法

    alt 隨機決策桌
        決策桌 -> 資料庫: 新增隨機決策桌
        決策桌 <-- 資料庫: 回應結果
    else 投票決策桌
        決策桌 -> 資料庫: 新增投票決策桌
        決策桌 <-- 資料庫: 回應結果
    else T字決策桌
        決策桌 -> 資料庫: 新增T字決策桌
        決策桌 <-- 資料庫: 回應結果
    end
    User <-- 決策桌: 顯示結果
else 不合法
    User <-- 決策桌: 顯示重新輸入
    deactivate 決策桌
end
@enduml